config/routes.rb
UrlShortener::Application.routes.draw do
  resources :urls
  root :to => 'urls#index'
  match '/:alias' => 'urls#find'

end

app/models/url.rb
class Url < ActiveRecord::Base
  attr_accessible :alias, :url

  # validates_format_of :url, :with => URI::regexp(%w(http https))
  before_save :create_alias

  def create_alias
  	self.alias = rand(36**6).to_s(36)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  # GET /urls
  # GET /urls.json
  def index
    @url = Url.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @urls }
    end
  end

  # GET /urls/new
  # GET /urls/new.json
  def new
    @url = Url.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @url }
    end
  end

  def create
    @url = Url.new(params[:url])

    respond_to do |format|
      if @url.save
        format.html {  }#redirect_to @url, notice: 'Url was successfully created.'
        format.json { render json: @url, status: :created, location: @url }
      else
        format.html { render action: "new" }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  def error_method

  end

  def find
    @alias = params[:alias]
    @url = Url.where(:alias => @alias).first

    respond_to do |format|
      format.html { redirect_to @url.url }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<title>UrlShortener - JusBrasil</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
	<%= csrf_meta_tags %>
</head>
<body>
	
	<%= yield %>
	
	<%= javascript_include_tag "application" %>

	<script>
		$(document).ready(initialize);
	</script>
</body>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url, :remote => true) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :url, :placeholder => "Digite a URL", :autocomplete => :off, :required => true%>
  </div>
 
  <div class="actions">
    <button class="btnSubmit">Go!</button>
  </div>
<% end %>

app/views/urls/_header.html.erb
<header class="header">
	<%= link_to	"UrlShortener", root_path, :class => 'title' %> 
	 
</header>

app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<%= render 'header' %>

<div class="content">
  <div class="errors"></div>

  <%= render 'form' %>

  <div class="formatted">
    <h3 class="titleUrlBox">Feito! Copie seu link</h3>
    <p class="urlShortener"></p>
  </div>
</div>

app/views/urls/new.html.erb
<h1>New url</h1>

<%= render 'form' %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @url.url %>
</p>

<p>
  <b>Alias:</b>
  <%= @url.alias %>
</p>


<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>